approvals_reviewer = "user"
service_tier = "fast"
[projects."/home/bits/go/src/github.com/DataDog/dd-source"]
trust_level = "trusted"

[projects."/home/bits/go/src/github.com/DataDog/dd-source-2"]
trust_level = "trusted"

[projects."/home/bits/.local/share/chezmoi"]
trust_level = "trusted"

[tui]
status_line = [
    "model-with-reasoning",
    "current-dir",
    "git-branch",
    "pull-request-number",
    "branch-changes",
    "run-state",
    "context-used",
    "fast-mode",
    "task-progress",
]
status_line_use_colors = true
vim_mode_default = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."atlassian-rovo@openai-curated"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."workspaces@datadog-claude-plugins"]
enabled = true

[plugins."atlassian-api@datadog-claude-plugins"]
enabled = true

[plugins."dd@datadog-claude-plugins"]
enabled = true

[features]
terminal_resize_reflow = true

[marketplaces.datadog-claude-plugins]
last_updated = "2026-05-14T21:20:03Z"
last_revision = "3cf73c5a1fe9ab4cb81de8a59cdd3bff3047f262"
source_type = "git"
source = "https://github.com/DataDog/claude-marketplace.git"
